name: " Reporte de Bug"
description: "Reporta un problema para ayudarnos a mejorar la extensi贸n."
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: "Versi贸n de la extensi贸n"
      placeholder: "Ejemplo: v1.0.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripci贸n del problema"
      description: "Explica qu茅 ocurre y qu茅 esperabas que pasara."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducir"
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs o evidencia"
      description: "Agrega capturas o errores si aplica."
      placeholder: "Contenido opcional"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "Sistema operativo"
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
